// <auto-generated />
using System;
using HisabPro.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HisabPro.Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241210063914_AddedUserGender")]
    partial class AddedUserGender
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HisabPro.Entities.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.ChildCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ChildCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mobile",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watch",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electric",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Maintenance",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Property Tax",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kitchen",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bathroom",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rooms",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bread",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Milk",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Buttermilk",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Curd",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Juice",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Coldrink",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Icecreame",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Egg",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pulses (Kathol)",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dalaman",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Lunch",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dinner",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Parcel",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nasto",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vegitables",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Masala",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fruits",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fish",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mango",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sweets",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chicken",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Oil",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bakery Items",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mutton",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dr Visit (Appointment)",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Reports",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Toothpaste",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Medicine",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sadaka",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saiyad Saheb",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Donation",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Molvi Saheb",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mujawar",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dargah",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nyaz",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 44,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Help",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 45,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Imam Bargah",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 46,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Masjid",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 47,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Zakat & Khums",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 48,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watchman",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 49,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal Expense",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 50,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mobile Recharge",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 51,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fast Tag",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 52,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fees",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 53,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tution",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 54,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Stationary",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 55,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Text Books",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 56,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Note Books",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 57,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "School Dress",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 58,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hotel",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 59,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Picnic",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 60,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 61,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cloths",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 62,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Life Insurance",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 63,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Islamic",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 64,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gift",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 65,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hair Cut",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 66,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Transportation",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 67,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Beauty",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 68,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Shooe",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 69,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Diaper",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 70,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Petrol",
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 71,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "GAS",
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 72,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CAR",
                            ParentCategoryId = 7
                        },
                        new
                        {
                            Id = 73,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cash",
                            ParentCategoryId = 16
                        },
                        new
                        {
                            Id = 74,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Online Transfer",
                            ParentCategoryId = 16
                        },
                        new
                        {
                            Id = 75,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mall",
                            ParentCategoryId = 2
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ChildCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpenseOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ChildCategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IncomeOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.ParentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("ParentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "House Hold Items"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Offline Shopping"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Online Shopping"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bills"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vehical Service"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Donation"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal Care"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Recharge"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour (Picnic)"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Investment"
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            Email = "Imdadhusen.sunasara@gmail.com",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Imdadhusen",
                            PasswordHash = "1vMi372tmTXw2LgItnQRh9bvTS88Am8ob0wfInqrdBXIV+1sIdcsw4j+48P2rUP2Kyt+UazOik1Yoflvdx+EwQ==",
                            PasswordSalt = "xw6EbrRY1TTO1ef1Hclk4zFtWbfcHnTZgaw/K9+n05wYIKlaywZyRmn9VC0vGzklp1JaSQjtKoI0Wmf6FgUR4xbou/QJvqJlvzlYCLdrYbfXUyoLwdFJ90eNESfIHu8OfxGpzeKi8ceSEG6hieoEMnCp/wFnOogdGpz93pR1msU=",
                            UserRole = 1
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Account", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.ChildCategory", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HisabPro.Entities.Models.ParentCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Expense", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.Account", "Account")
                        .WithMany("Expenses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.ChildCategory", "ChildCategory")
                        .WithMany()
                        .HasForeignKey("ChildCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HisabPro.Entities.Models.ParentCategory", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ChildCategory");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Income", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.Account", "Account")
                        .WithMany("Incomes")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.ParentCategory", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.User", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Account", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.ParentCategory", b =>
                {
                    b.Navigation("ChildCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
