// <auto-generated />
using System;
using HisabPro.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HisabPro.Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241221055208_RemoveParentNChildTables")]
    partial class RemoveParentNChildTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HisabPro.Entities.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "House Hold Items",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Offline Shopping",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Online Shopping",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Bills",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Insurance",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Education",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Vehical Service",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Fuel",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Donation",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Food",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Doctor",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Personal Care",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Recharge",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Tour (Picnic)",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Personal",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Investment",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Pulses (Kathol)",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Dalaman",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Lunch",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Dinner",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Parcel",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Nasto",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Vegitables",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Masala",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Fruits",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Fish",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Mango",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Sweets",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Chicken",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Oil",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Bakery Items",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Mutton",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Dr Visit (Appointment)",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Reports",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Toothpaste",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Medicine",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Sadaka",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Saiyad Saheb",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Donation",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Molvi Saheb",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Mujawar",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Dargah",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Nyaz",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Help",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 45,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Imam Bargah",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 46,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Masjid",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 47,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Zakat & Khums",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 48,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Watchman",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 49,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Personal Expense",
                            ParentId = 15,
                            Type = 1
                        },
                        new
                        {
                            Id = 50,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Mobile Recharge",
                            ParentId = 13,
                            Type = 1
                        },
                        new
                        {
                            Id = 51,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Fast Tag",
                            ParentId = 13,
                            Type = 1
                        },
                        new
                        {
                            Id = 52,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Fees",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 53,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Tution",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 54,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Stationary",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 55,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Text Books",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 56,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Note Books",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 57,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "School Dress",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 58,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Hotel",
                            ParentId = 14,
                            Type = 1
                        },
                        new
                        {
                            Id = 59,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Picnic",
                            ParentId = 14,
                            Type = 1
                        },
                        new
                        {
                            Id = 60,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Tour",
                            ParentId = 14,
                            Type = 1
                        },
                        new
                        {
                            Id = 61,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Cloths",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 62,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Life Insurance",
                            ParentId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 63,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Islamic",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 64,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Gift",
                            ParentId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 65,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Hair Cut",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 66,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Transportation",
                            ParentId = 15,
                            Type = 1
                        },
                        new
                        {
                            Id = 67,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Beauty",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 68,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Shooe",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 69,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Diaper",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 70,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Petrol",
                            ParentId = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 71,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "GAS",
                            ParentId = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 72,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "CAR",
                            ParentId = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 73,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Cash",
                            ParentId = 16,
                            Type = 1
                        },
                        new
                        {
                            Id = 74,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Online Transfer",
                            ParentId = 16,
                            Type = 1
                        },
                        new
                        {
                            Id = 75,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Mall",
                            ParentId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 76,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Mobile",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 77,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Watch",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 78,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Electric",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 79,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Maintenance",
                            ParentId = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = 80,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Property Tax",
                            ParentId = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = 81,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Kitchen",
                            ParentId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 82,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Bathroom",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 83,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Rooms",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 84,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Bread",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 85,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Milk",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 86,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Buttermilk",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 87,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Curd",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 88,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Juice",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 89,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Coldrink",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 90,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Icecreame",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 91,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Egg",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 92,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Job",
                            Type = 2
                        },
                        new
                        {
                            Id = 93,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Business",
                            Type = 2
                        },
                        new
                        {
                            Id = 94,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Gift",
                            Type = 2
                        },
                        new
                        {
                            Id = 95,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Investment",
                            Type = 2
                        },
                        new
                        {
                            Id = 96,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Item Sold",
                            Type = 2
                        },
                        new
                        {
                            Id = 97,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Insurance",
                            Type = 2
                        },
                        new
                        {
                            Id = 98,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Salary",
                            ParentId = 92,
                            Type = 2
                        },
                        new
                        {
                            Id = 99,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Incentive",
                            ParentId = 92,
                            Type = 2
                        },
                        new
                        {
                            Id = 100,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Bonus",
                            ParentId = 92,
                            Type = 2
                        },
                        new
                        {
                            Id = 101,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Performance",
                            ParentId = 92,
                            Type = 2
                        },
                        new
                        {
                            Id = 102,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Profit",
                            ParentId = 93,
                            Type = 2
                        },
                        new
                        {
                            Id = 103,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Capital",
                            ParentId = 93,
                            Type = 2
                        },
                        new
                        {
                            Id = 104,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Soldout",
                            ParentId = 93,
                            Type = 2
                        },
                        new
                        {
                            Id = 105,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Social Function",
                            ParentId = 94,
                            Type = 2
                        },
                        new
                        {
                            Id = 106,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Personal",
                            ParentId = 94,
                            Type = 2
                        },
                        new
                        {
                            Id = 107,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Lucky Draw",
                            ParentId = 94,
                            Type = 2
                        },
                        new
                        {
                            Id = 108,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Property",
                            ParentId = 95,
                            Type = 2
                        },
                        new
                        {
                            Id = 109,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Bank Interest",
                            ParentId = 95,
                            Type = 2
                        },
                        new
                        {
                            Id = 110,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Society",
                            ParentId = 95,
                            Type = 2
                        },
                        new
                        {
                            Id = 111,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Stationary",
                            ParentId = 96,
                            Type = 2
                        },
                        new
                        {
                            Id = 112,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Scrap (Bhangar)",
                            ParentId = 96,
                            Type = 2
                        },
                        new
                        {
                            Id = 113,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Vehicale",
                            ParentId = 96,
                            Type = 2
                        },
                        new
                        {
                            Id = 114,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "House Hold Item",
                            ParentId = 96,
                            Type = 2
                        },
                        new
                        {
                            Id = 115,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Insurance Maturity",
                            ParentId = 97,
                            Type = 2
                        },
                        new
                        {
                            Id = 116,
                            CreatedBy = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsStandard = true,
                            Name = "Insurance Return",
                            ParentId = 97,
                            Type = 2
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpenseOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBulkImported")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IncomeOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBulkImported")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            Email = "Imdadhusen.sunasara@gmail.com",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Mobile = "9909544184",
                            Name = "Imdadhusen",
                            PasswordHash = "1vMi372tmTXw2LgItnQRh9bvTS88Am8ob0wfInqrdBXIV+1sIdcsw4j+48P2rUP2Kyt+UazOik1Yoflvdx+EwQ==",
                            PasswordSalt = "xw6EbrRY1TTO1ef1Hclk4zFtWbfcHnTZgaw/K9+n05wYIKlaywZyRmn9VC0vGzklp1JaSQjtKoI0Wmf6FgUR4xbou/QJvqJlvzlYCLdrYbfXUyoLwdFJ90eNESfIHu8OfxGpzeKi8ceSEG6hieoEMnCp/wFnOogdGpz93pR1msU=",
                            UserRole = 2
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Account", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Category", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HisabPro.Entities.Models.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Expense", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.Account", "Account")
                        .WithMany("Expenses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HisabPro.Entities.Models.Category", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Income", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.Account", "Account")
                        .WithMany("Incomes")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HisabPro.Entities.Models.Category", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.User", b =>
                {
                    b.HasOne("HisabPro.Entities.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Models.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Account", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("HisabPro.Entities.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
