// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleMvcCoreApp.Entities;

#nullable disable

namespace SampleMvcCoreApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240623120955_ParantChildCategory")]
    partial class ParantChildCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetail = "Ahmedabad",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9984),
                            EmployeeId = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AddressDetail = "Surat",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9987),
                            EmployeeId = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AddressDetail = "Patan",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9988),
                            EmployeeId = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            AddressDetail = "Siddhpur",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9990),
                            EmployeeId = 3,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            AddressDetail = "Palanpur",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9992),
                            EmployeeId = 4,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            AddressDetail = "Ahmedabad",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9994),
                            EmployeeId = 5,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.ChildCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ChildCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(131),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mobile",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(133),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watch",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(225),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electric",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(227),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Maintenance",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(228),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Property Tax",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(231),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kitchen",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(233),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bathroom",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(234),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rooms",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(236),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bread",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(238),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Milk",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(239),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Buttermilk",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(241),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Curd",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(242),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Juice",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(244),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Coldrink",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(246),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Icecreame",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(247),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Egg",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(249),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pulses (Kathol)",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(251),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dalaman",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(252),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Lunch",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(254),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dinner",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(255),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Parcel",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(257),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nasto",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(259),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vegitables",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(260),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Masala",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(262),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fruits",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(263),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fish",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(265),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mango",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(266),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sweets",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(268),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chicken",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(270),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Oil",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(271),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bakery Items",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(273),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mutton",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(274),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dr Visit (Appointment)",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(276),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Reports",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(278),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Toothpaste",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(279),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Medicine",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(281),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sadaka",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(282),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saiyad Saheb",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(284),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Donation",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(286),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Molvi Saheb",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(287),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mujawar",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(289),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dargah",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(290),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nyaz",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 44,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(292),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Help",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 45,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(294),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Imam Bargah",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 46,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(295),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Masjid",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 47,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(297),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Zakat & Khums",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 48,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(298),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watchman",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 49,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(300),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal Expense",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 50,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(301),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mobile Recharge",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 51,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(303),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fast Tag",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 52,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(304),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fees",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 53,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(306),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tution",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 54,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(307),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Stationary",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 55,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(309),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Text Books",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 56,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(311),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Note Books",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 57,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(312),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "School Dress",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 58,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(315),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hotel",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 59,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(316),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Picnic",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 60,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(318),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 61,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(320),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cloths",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 62,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(321),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Life Insurance",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 63,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(323),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Islamic",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 64,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(324),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gift",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 65,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(326),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hair Cut",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 66,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(327),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Transportation",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 67,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(329),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Beauty",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 68,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(330),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Shooe",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 69,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(332),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Diaper",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 70,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(334),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Petrol",
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 71,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(337),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "GAS",
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 72,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(339),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CAR",
                            ParentCategoryId = 7
                        });
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DepartmentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(26),
                            DepartmentName = "Development",
                            DepartmentPhone = "9909544184",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(28),
                            DepartmentName = "Testing",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(30),
                            DepartmentName = "Human Resource",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(31),
                            DepartmentName = "Finance",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(33),
                            DepartmentName = "Marketing",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(35),
                            DepartmentName = "Admin",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9620),
                            DepartmentId = 1,
                            Email = "Test@test.com",
                            EmployeeName = "Test Emp1",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test1",
                            Skill = "Test1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9625),
                            DepartmentId = 2,
                            Email = "Test2@test.com",
                            EmployeeName = "Test Emp2",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test2",
                            Skill = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9628),
                            DepartmentId = 3,
                            Email = "Test3@test.com",
                            EmployeeName = "Test Emp3",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test3",
                            Skill = "Test3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9631),
                            DepartmentId = 4,
                            Email = "SoftDelete@test.com",
                            EmployeeName = "Soft Deleted Employee",
                            IsActive = true,
                            IsDeleted = true,
                            Password = "Deleted",
                            Skill = "Soft Delete"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 309, DateTimeKind.Utc).AddTicks(9633),
                            DepartmentId = 4,
                            Email = "Inactive@test.com",
                            EmployeeName = "Inactive Employee",
                            IsActive = false,
                            IsDeleted = false,
                            Password = "Inactive",
                            Skill = "In Active"
                        });
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.ParentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(67),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "House Hold Items"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(69),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Offline Shopping"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(71),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Online Shopping"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(73),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bills"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(75),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(77),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(78),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vehical Service"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(80),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(82),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Donation"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(83),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(85),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(87),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal Care"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(88),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Recharge"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(90),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour (Picnic)"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 12, 9, 55, 310, DateTimeKind.Utc).AddTicks(92),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Address", b =>
                {
                    b.HasOne("SampleMvcCoreApp.Entities.Employee", "Employee")
                        .WithMany("EmployeeAddress")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.ChildCategory", b =>
                {
                    b.HasOne("SampleMvcCoreApp.Entities.ParentCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Employee", b =>
                {
                    b.HasOne("SampleMvcCoreApp.Entities.Department", "Department")
                        .WithMany("Employee")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Department", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeAddress");
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.ParentCategory", b =>
                {
                    b.Navigation("ChildCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
