// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleMvcCoreApp.Entities;

#nullable disable

namespace SampleMvcCoreApp.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20240609090413_IsDeletedForAllTable")]
    partial class IsDeletedForAllTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetail = "Ahmedabad",
                            EmployeeId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AddressDetail = "Surat",
                            EmployeeId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AddressDetail = "Patan",
                            EmployeeId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            AddressDetail = "Siddhpur",
                            EmployeeId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            AddressDetail = "Palanpur",
                            EmployeeId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            AddressDetail = "Ahmedabad",
                            EmployeeId = 5,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DepartmentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Development",
                            DepartmentPhone = "9909544184",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Testing",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Human Resource",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Finance",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Marketing",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            DepartmentName = "Admin",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "Test@test.com",
                            EmployeeName = "Test Emp1",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test1",
                            Skill = "Test1"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "Test2@test.com",
                            EmployeeName = "Test Emp2",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test2",
                            Skill = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "Test3@test.com",
                            EmployeeName = "Test Emp3",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test3",
                            Skill = "Test3"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Email = "SoftDelete@test.com",
                            EmployeeName = "Soft Deleted Employee",
                            IsActive = true,
                            IsDeleted = true,
                            Password = "Deleted",
                            Skill = "Soft Delete"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 4,
                            Email = "Inactive@test.com",
                            EmployeeName = "Inactive Employee",
                            IsActive = false,
                            IsDeleted = false,
                            Password = "Inactive",
                            Skill = "In Active"
                        });
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Address", b =>
                {
                    b.HasOne("SampleMvcCoreApp.Entities.Employee", "Employee")
                        .WithMany("EmployeeAddress")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Employee", b =>
                {
                    b.HasOne("SampleMvcCoreApp.Entities.Department", "Department")
                        .WithMany("Employee")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Department", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SampleMvcCoreApp.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
