// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using HisabPro.Entities;

#nullable disable

namespace HisabPro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240623132654_ReferenceForCreator")]
    partial class ReferenceForCreator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HisabPro.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetail = "Ahmedabad",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6024),
                            EmployeeId = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AddressDetail = "Surat",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6026),
                            EmployeeId = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AddressDetail = "Patan",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6028),
                            EmployeeId = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            AddressDetail = "Siddhpur",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6030),
                            EmployeeId = 3,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            AddressDetail = "Palanpur",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6032),
                            EmployeeId = 4,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            AddressDetail = "Ahmedabad",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6033),
                            EmployeeId = 5,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.ChildCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ChildCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6239),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mobile",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6241),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watch",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6242),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electric",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6244),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Maintenance",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6246),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Property Tax",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6248),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kitchen",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6250),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bathroom",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6252),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rooms",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6253),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bread",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6255),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Milk",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6257),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Buttermilk",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6259),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Curd",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6261),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Juice",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6262),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Coldrink",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6264),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Icecreame",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6266),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Egg",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6268),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pulses (Kathol)",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6270),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dalaman",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6272),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Lunch",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6274),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dinner",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6276),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Parcel",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6277),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nasto",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6279),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vegitables",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6281),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Masala",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6282),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fruits",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6284),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fish",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6286),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mango",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6287),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sweets",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6289),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chicken",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6291),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Oil",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6292),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bakery Items",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6294),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mutton",
                            ParentCategoryId = 10
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6296),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dr Visit (Appointment)",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6299),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Reports",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6300),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Toothpaste",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6302),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Medicine",
                            ParentCategoryId = 11
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6304),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sadaka",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6306),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saiyad Saheb",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6307),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Donation",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6309),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Molvi Saheb",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6311),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mujawar",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6312),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dargah",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6314),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nyaz",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 44,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6316),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Help",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 45,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6317),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Imam Bargah",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 46,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6353),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Masjid",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 47,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6355),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Zakat & Khums",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 48,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6357),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watchman",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 49,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6358),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal Expense",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 50,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6360),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mobile Recharge",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 51,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6362),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fast Tag",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 52,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6363),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fees",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 53,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6366),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tution",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 54,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6368),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Stationary",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 55,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6370),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Text Books",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 56,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6371),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Note Books",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 57,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6373),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "School Dress",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 58,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6375),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hotel",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 59,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6376),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Picnic",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 60,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6378),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 61,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6380),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cloths",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 62,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6381),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Life Insurance",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 63,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6383),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Islamic",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 64,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6385),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gift",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 65,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6387),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hair Cut",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 66,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6388),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Transportation",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 67,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6390),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Beauty",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 68,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6391),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Shooe",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 69,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6393),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Diaper",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            Id = 70,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6395),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Petrol",
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 71,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6396),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "GAS",
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 72,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6398),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CAR",
                            ParentCategoryId = 7
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DepartmentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6065),
                            DepartmentName = "Development",
                            DepartmentPhone = "9909544184",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6067),
                            DepartmentName = "Testing",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6142),
                            DepartmentName = "Human Resource",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6144),
                            DepartmentName = "Finance",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6146),
                            DepartmentName = "Marketing",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6148),
                            DepartmentName = "Admin",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(5744),
                            DepartmentId = 1,
                            Email = "Test@test.com",
                            EmployeeName = "Test Emp1",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test1",
                            Skill = "Test1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(5749),
                            DepartmentId = 2,
                            Email = "Test2@test.com",
                            EmployeeName = "Test Emp2",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test2",
                            Skill = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(5752),
                            DepartmentId = 3,
                            Email = "Test3@test.com",
                            EmployeeName = "Test Emp3",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Test3",
                            Skill = "Test3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(5754),
                            DepartmentId = 4,
                            Email = "SoftDelete@test.com",
                            EmployeeName = "Soft Deleted Employee",
                            IsActive = true,
                            IsDeleted = true,
                            Password = "Deleted",
                            Skill = "Soft Delete"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(5756),
                            DepartmentId = 4,
                            Email = "Inactive@test.com",
                            EmployeeName = "Inactive Employee",
                            IsActive = false,
                            IsDeleted = false,
                            Password = "Inactive",
                            Skill = "In Active"
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.ParentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("ParentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6179),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "House Hold Items"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6181),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Offline Shopping"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6183),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Online Shopping"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6185),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bills"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6188),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6190),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6192),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vehical Service"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6193),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6195),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Donation"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6197),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6199),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6201),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal Care"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6202),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Recharge"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6204),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour (Picnic)"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(6206),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 6, 23, 13, 26, 53, 463, DateTimeKind.Utc).AddTicks(5996),
                            Email = "Imdadhusen.sunasara@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Imdadhusen",
                            Password = "imdad@123"
                        });
                });

            modelBuilder.Entity("HisabPro.Entities.Address", b =>
                {
                    b.HasOne("HisabPro.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Employee", "Employee")
                        .WithMany("EmployeeAddress")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Employee");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.ChildCategory", b =>
                {
                    b.HasOne("HisabPro.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HisabPro.Entities.ParentCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("HisabPro.Entities.Department", b =>
                {
                    b.HasOne("HisabPro.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.Employee", b =>
                {
                    b.HasOne("HisabPro.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.Department", "Department")
                        .WithMany("Employee")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Department");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.ParentCategory", b =>
                {
                    b.HasOne("HisabPro.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.User", b =>
                {
                    b.HasOne("HisabPro.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HisabPro.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("HisabPro.Entities.Department", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HisabPro.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeAddress");
                });

            modelBuilder.Entity("HisabPro.Entities.ParentCategory", b =>
                {
                    b.Navigation("ChildCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
